{% set version = "1.9.0" %}

package:
  name: libspatialindex
  version: {{ version }}

source:
  url: https://github.com/libspatialindex/libspatialindex/archive/{{ version }}.tar.gz
  sha256: 7c8809cd7e827efdc8bd80f786cf2a2d4f25adb92f954d46f7f28ad410bd46e2
  patches:
    - tool.h.patch  # [win and vc>=14]
    - cmakelists.patch  # [win and vc>=14]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libspatialindex_c${SHLIB_EXT}  # [not win]

about:
  home: http://libspatialindex.github.io
  license: MIT
  license_file: COPYING
  summary: 'Extensible framework for robust spatial indexing'

extra:
  recipe-maintainers:
    - ocefpaf
