{% set version = "1.8.5" %}

package:
  name: libspatialindex
  version: {{ version }}

source:
  url: http://download.osgeo.org/libspatialindex/spatialindex-src-{{ version }}.tar.gz
  sha256: 7caa46a2cb9b40960f7bc82c3de60fa14f8f3e000b02561b36cbf2cfe6a9bfef
  patches:
    - tool.h.patch  # [win and vc14]
    - cmakelists.patch  # [win and vc14]

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libspatialindex_c.so  # [linux]
    - test -f ${PREFIX}/lib/libspatialindex_c.dylib  # [osx]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://libspatialindex.github.io
  license: MIT
  license_file: COPYING
  summary: 'Extensible framework for robust spatial indexing.'

extra:
  recipe-maintainers:
    - ocefpaf
