{% set version = "1.8.5" %}

package:
  name: libspatialindex
  version: {{ version }}

source:
  fn: spatialindex-src-{{ version }}.tar.gz
  url: http://download.osgeo.org/libspatialindex/spatialindex-src-{{ version }}.tar.gz
  sha256: 7caa46a2cb9b40960f7bc82c3de60fa14f8f3e000b02561b36cbf2cfe6a9bfef
  patches:
    - tool.h.patch  # [win and py>=35]
    - cmakelists.patch  # [win and py>=35]

build:
  number: 1
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - python  # [win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
  run:
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]

test:
  commands:
    - test -f ${PREFIX}/lib/libspatialindex_c.so  # [linux]
    - test -f ${PREFIX}/lib/libspatialindex_c.dylib  # [osx]
    - conda inspect linkages -p $PREFIX libspatialindex  # [not win]
    - conda inspect objects -p $PREFIX libspatialindex  # [osx]

about:
  home: http://libspatialindex.github.io
  license: MIT
  license_file: COPYING
  summary: 'Extensible framework for robust spatial indexing.'

extra:
  recipe-maintainers:
    - ocefpaf
