{% set version = "1.9.0" %}

package:
  name: libspatialindex
  version: {{ version }}

source:
  url: https://github.com/libspatialindex/libspatialindex/archive/{{ version }}.tar.gz
  sha256: 52d6875deea12f88e6918d192cbfd38d6e78d13f84e1fd10cca66132fa063941
  patches:
    - tool.h.patch  # [win and vc>=14]
    - cmakelists.patch  # [win and vc>=14]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libspatialindex_c${SHLIB_EXT}  # [not win]

about:
  home: http://libspatialindex.github.io
  license: MIT
  license_file: COPYING
  summary: 'Extensible framework for robust spatial indexing'

extra:
  recipe-maintainers:
    - ocefpaf
