# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "r6XuwVlACBx+mk57WRlzwTlkKRY9c/CJUDYW/rVDrcDE3IsD8pATMcm+m85OIUYZ3n8gdLFnqRO1xV6ROsoiqvsdmnX+1ooUyVEB8wIAoSjqkYlDCpTsunVbI/tZSXh6IaryuxlO+aaSPqGSh8qnXFsi59efBrgrRYTffEjQ7dbAccHVqO9O/paqa783tN1UP9HmjDaOPIczMjobnN91hkSn8vUIirl1H/d/2n3qdp6w7YYcxCO3GeN0bxgskBmq7LtBJmOUJaViOCAh+U+6+WnWbjs7GYvdIbZdrMtUEiZozSEhbnKukAEPAUh5ZXdgMjR6gfVOnTjov4Rd2Yb+xEBBnyAyEcDgX23LovnbnogWe9Y0z1n/iMqmSOnPxf/j/TbDBhWVozcpZc0O5eFL0dFWNhCK3edFefKa8n9DLjFfK8eh1FzSof37pyttp0eC/4/9L3ekVtnny8S+3GWeMDlHCYUtTPmmvH2BYqfISfSbgGRtRC7szDup5sjcJn5Ten4TyEtJCN+TbhKXXDINJNk2ztG0SPlDKtUDx//YgCBgjRhj3V39A69V0tmwg/d+NheBFDT7Og4SloTrZFANbGatQfUk0b3knjGUyfdVgiyw2BmO30gZTbTurnNJdGWvl6138g+Tshq1jA9EaTgET8cvi7QrgtcCU0e3BWgk1F8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml

  - conda config --remove channels defaults --force

  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
