travis:
  secure:
    BINSTAR_TOKEN: aiyvtvjTlYIbE5nngHWoPwDBb9AqgfcfNjKrUPqEftzJC6QNandk0XTEvNX3Efp5x4ugLT4p/Cqsnx6JoUJ7OsZ7bemipCCQJ2jlylBTXdpX32rubK3kG9w2KGX6Mr+hEcxll6CkaNNMfKJP6SiatsRx8OMJpdSbW89diVCBVR/UnZi7v0qvK+QE33OPqKPj6ulfFJDBfrTJc0vA17guO8jo/SJbE/rBHJNKX1tNSiQIayOiHCri9FRpnR2gB8kgW2Mb6Vjcz3STkE92ZU7/FWkueKOkwpHRsxgoqEDWPyUCkCxcn+D3w7mblX9cE+xYbui5Js7y6wa9AyqZtvq3YvbHPLpKaAMfg9+7oY5QFuIVPAn+5iyazDK8B4nGDl5jJyp8arFP25RzWgZCJbN3dmQCgVrXuvKdp5zr8C1c8266chS8hpG+BY6dc7Aiy5F0hYbw294DCKs6EfEnUpbN3/McNgPMqSiB9m0H0F2qyAZ/wrrEQ9v3YE3xNQQwTy2EHjyBpEs8W6bgtuo/7HcpUR0BFNEYfCaDdXr+y8zje638GnBI3DO8Y9sl+YDaHZHq1yF2JFWcVtoQaOqytQ4YAnVZqYdytngBkJGJZqoVTyp5u7i6zs9ZFZV1pWoysoGvDe/WbMeJE0gZXUrlVYooWqXg9N6hKMPW+mQ4dUdV1SQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
